### PR TITLE
Updated README.md with Course Timestamps

### PR DESCRIPTION
**Pull request by DezlyMacauley**
I've added a "Course Timestamps" section to README.md

You can find this new section after "Bridging to Arbitrum"

This is a response to: https://github.com/Cyfrin/foundry-full-course-f23/issues/11

### CODE REVIEW

**Comment by devblixt** [comment]
This is a lot of work, great!

**Comment by PatrickAlphaC** [comment]
Thanks for this! Two points.

1. You made a lot of formatting changes, perhaps your auto-format was a little aggressive and it's making it hard for me to review this. Could you update the formatting? 
2. Could we place these time stamps at their respective sections instead of all in one place? Thank you!

**Comment by DezlyMacauley** [comment]
Hey Patrick
Apologies for the formatting it's my first time working with a .md file. 
This was probably due to the "format on save function" being enabled on my VS Code, so that must have modified the existing formatting on the sections of README.md I didn't work on. 

😀🗒✍ I'll take this as a learning opportunity  so this doesn't happen in the future.

**Comment by PatrickAlphaC** [comment]
@DezlyMacauley no worries! And yes! The more you work in the industry, the better at these you will get

**Pull request closed without merging**
