### PR TITLE
Update README.md For chapter 7 [Make File]

### PR DESCRIPTION
**Pull request by DevSwayam**
#### Description
The Install Make Command for Users who have installed Ubantu as a VM in Windows was not working; hence, I added the alternative link, which is from the official documentation with a tutorial.

### CODE REVIEW

**Comment by ChefAharoni** [comment]
Hey, please note that you have misspelled Ubuntu. You accidentally wrote *Ubantu* instead of **Ubuntu**.

**Comment by DevSwayam** [comment]
> Hey, please note that you have misspelled Ubuntu. You accidentally wrote _Ubantu_ instead of **Ubuntu**.

Is it good sir?

**Comment by ChefAharoni** [comment]
> Is it good sir?

Yes, that it great.

**Comment by PatrickAlphaC** [comment]
ty :)

**Pull request merged**
