### PR TITLE
adding descriptions for the lesson 1-6

### PR DESCRIPTION
**Pull request by cromewar**
### Proposal 
Added a detailed description for lesson 1 to 6.

### CODE REVIEW

**Comment by PatrickAlphaC** [comment]
Lovely. I'll add this in soon. 

I just want to make a few touch ups myself first.

**Comment by PatrickAlphaC** [comment]
@cromewar I broke it 😅

Can you resolve conflicts and push again?

**Comment by cromewar** [comment]
With add this with the changes to chronological issues.

**Comment by PatrickAlphaC** [comment]
Going to close for now, feel free to follow up

**Pull request closed without merging**
